# vim:ft=kitty
## name: oscuravscode
## author: ported from oscura-vscode.nvim
## blurb: Oscura VSCode palette (true black)

# Base colors
foreground              #C2C2C2
background              #000000
selection_foreground    #C2C2C2
selection_background    #094770

# Cursor colors
cursor                  #4A88C7
cursor_text_color       #000000

# kitty window border colors
active_border_color     #323232
inactive_border_color   #2D2D2D

# Tab bar colors
active_tab_foreground   #C2C2C2
active_tab_background   #1E1E1E
inactive_tab_foreground #6E6F7A
inactive_tab_background #000000

# black
color0  #000000
color8  #3A3A3A

# red
color1  #FF5C5C
color9  #FF5C5C

# green
color2  #DCDCAA
color10 #B5CEA8

# yellow
color3  #B5CEA8
color11 #D7BA7D

# blue
color4  #659CD6
color12 #4A88C7

# magenta
color5  #569CD6
color13 #CE9178

# cyan
color6  #54C0A3
color14 #5ADBB0

# white
color7  #C2C2C2
color15 #FFFFFF
